name: CI/CD PIPELINE TO BUILD AND DEPLOY TO TOMCAT 

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Validate with Maven
        run: mvn validate

      - name: Compile with Maven
        run: mvn compile

      - name: Test with Maven
        run: mvn test

      - name: Package WAR
        run: mvn clean package -DskipTests

      - name: Verify WAR
        run: ls -lh target/petclinic.war

      - name: Check Sonar Configuration
        run: |
               echo "===== POM Sonar plugin ====="
               grep -n -A5 -B2 "sonar-maven-plugin" pom.xml || true

               echo "===== Maven version ====="
                mvn -version

                echo "===== Current directory ====="
                pwd

               echo "===== POM files ====="
               find . -name pom.xml -print
      
      - name: SonarQube Analysis
       run: |
             mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
             -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
             -Dsonar.token=${{ secrets.SONAR_TOKEN }}
      - name: Deploy WAR to Nexus
        run: |
          mvn deploy -DskipTests

      - name: Deploy WAR to Tomcat
        run: |
          curl --upload-file target/petclinic.war \
            -u "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
            "${{ secrets.TOMCAT_URL }}/manager/text/deploy?path=/train-ticket&update=true"
